[features]
seeds = false
[programs.localnet]
wmp_staking = "zCqMotQEKDpxkbv96kFS4p9XcCN19T48vtumdFe1GFd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://rpc.shyft.to?api_key=9beIuTTaz6bp2Mhf"
wallet = "/home/odmin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[toolchain]
anchor_version = "0.29.0"


